//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public string FoodCategory { get; set; }
        public string MfgDate { get; set; }
        public string ExpDate { get; set; }
        public int Quantity { get; set; }
        public int PerUnitPrice { get; set; }
        public string Ingredients { get; set; }
    }
}
